# Generated by Django 6.0 on 2026-01-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_constructora_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteexterno',
            name='rol',
            field=models.CharField(choices=[('director', 'Director (Ve toda la constructora)'), ('residente', 'Residente (Ve solo obras asignadas)'), ('remitente', 'Remitente (Solo crea remisiones)')], default='residente', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionariogeolab',
            name='area',
            field=models.CharField(choices=[('admin', 'Administrativo'), ('lab', 'Supervisor de Laboratorio'), ('recepcion', 'Recepción de Muestras'), ('tecnico', 'Técnico de Laboratorio')], max_length=50),
        ),
    ]
