# Generated by Django 6.0.2 on 2026-08-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_clienteexterno_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariogeolab',
            name='area',
            field=models.CharField(choices=[('admin', 'Administrativo'), ('lab', 'Supervisor de Laboratorio'), ('recepcion', 'Recepción de Muestras'), ('tecnico', 'Técnico de Laboratorio'), ('calidad', 'Coordinador de Calidad (solo SGC)')], max_length=50),
        ),
    ]
