# Generated by Django 6.0.2 on 2026-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_funcionariogeolab_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariogeolab',
            name='area',
            field=models.CharField(choices=[('admin', 'Administrativo'), ('lab', 'Supervisor de Laboratorio'), ('recepcion', 'Recepción de Muestras'), ('tecnico', 'Técnico de Laboratorio'), ('calidad', 'Coordinador de Calidad (solo SGC)'), ('calidad_usuario', 'Usuario de Calidad (solo carpetas asignadas)')], max_length=50),
        ),
    ]
