# Generated by Django 6.0 on 2025-12-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_obra', models.CharField(help_text='Ej: 52-1', max_length=50)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('id_wp_original', models.IntegerField(null=True, unique=True)),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='users.constructora')),
                ('residentes_asignados', models.ManyToManyField(blank=True, related_name='obras_asignadas', to='users.clienteexterno')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('url_archivo_original', models.CharField(blank=True, max_length=500, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='informes/%Y/%m/')),
                ('id_wp_original', models.IntegerField(null=True, unique=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='core.obra')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
