# Generated by Django 6.0.2 on 2026-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='celular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='obra',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='obra',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
