# Generated by Django 6.0.2 on 2026-08-13 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoCarpetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True, help_text='Abrir la carpeta y ver/descargar sus documentos.')),
                ('puede_cargar', models.BooleanField(default=False, help_text='Subir documentos y crear subcarpetas dentro de la carpeta.')),
                ('puede_eliminar', models.BooleanField(default=False, help_text='Eliminar documentos de la carpeta.')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_carpetas_asignados', to=settings.AUTH_USER_MODEL)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_usuarios', to='calidad.carpeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_carpetas_calidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso a Carpeta',
                'verbose_name_plural': 'Accesos a Carpetas',
                'unique_together': {('usuario', 'carpeta')},
            },
        ),
    ]
