# Generated by Django 6.0 on 2026-03-09 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0003_alter_clienteexterno_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicio',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Ej: 19.00 para 19%', max_digits=5, verbose_name='Porcentaje')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_periodo', models.DateField(verbose_name='Inicio del periodo')),
                ('fecha_fin_periodo', models.DateField(verbose_name='Fin del periodo')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Subtotal')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Monto IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('iva_transporte_facturado', models.BooleanField(default=False, help_text='Indica si se aplicó IVA a servicios de transporte', verbose_name='IVA transporte aplicado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('pdf_archivo', models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/', verbose_name='PDF')),
                ('constructora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='users.constructora', verbose_name='Constructora')),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='core.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('norma', models.CharField(blank=True, help_text='Norma técnica aplicable', max_length=100, verbose_name='Norma técnica')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='facturacion.categoriaservicio', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['categoria__codigo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de realización')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('numero_informe', models.CharField(help_text='Número del informe de laboratorio', max_length=100, verbose_name='Número de informe')),
                ('precio_unitario_congelado', models.DecimalField(decimal_places=2, help_text='Precio congelado al momento del registro', max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Subtotal')),
                ('facturar_despues', models.BooleanField(default=False, verbose_name='Facturar después')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_facturacion', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='facturacion.factura', verbose_name='Factura')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_servicio', to='core.obra', verbose_name='Obra')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='facturacion.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Registro de Servicio',
                'verbose_name_plural': 'Registros de Servicio',
                'ordering': ['-fecha_realizacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrecioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Dejar vacío si no aplica para esta obra', max_digits=12, null=True, verbose_name='Precio unitario')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_de_precios', to='core.obra', verbose_name='Obra')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.tiposervicio', verbose_name='Tipo de Servicio')),
            ],
            options={
                'verbose_name': 'Precio de Servicio',
                'verbose_name_plural': 'Precios de Servicio',
                'unique_together': {('obra', 'tipo_servicio')},
            },
        ),
    ]
