# Generated by Django 6.0.2 on 2026-09-14 17:58

from django.db import migrations, models

from facturacion.orden import clave_orden


def poblar_clave_orden(apps, schema_editor):
    """Calcula la clave de las filas existentes (las nuevas la reciben en save())."""
    for nombre_modelo in ('CategoriaServicio', 'TipoServicio'):
        Modelo = apps.get_model('facturacion', nombre_modelo)
        for fila in Modelo.objects.all().only('id', 'codigo'):
            fila.clave_orden = clave_orden(fila.codigo)
            fila.save(update_fields=['clave_orden'])


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ['clave_orden', 'codigo'], 'verbose_name': 'Categoría de Servicio', 'verbose_name_plural': 'Categorías de Servicio'},
        ),
        migrations.AlterModelOptions(
            name='tiposervicio',
            options={'ordering': ['categoria__clave_orden', 'categoria__codigo', 'clave_orden', 'codigo'], 'verbose_name': 'Tipo de Servicio', 'verbose_name_plural': 'Tipos de Servicio'},
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='clave_orden',
            field=models.CharField(db_index=True, default='', editable=False, max_length=60),
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='clave_orden',
            field=models.CharField(db_index=True, default='', editable=False, max_length=60),
        ),
        migrations.RunPython(poblar_clave_orden, migrations.RunPython.noop),
    ]
