"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'portalgeolab.com',
    'www.portalgeolab.com',	
    'localhost',   
    '127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = [
    'https://portalgeolab.com',
    'https://www.portalgeolab.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
    'core',
    'solicitudes',
    'ensayos',
    'calidad',
    'facturacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'  # Español Colombia

TIME_ZONE = 'America/Bogota'  # <--- HORA COLOMBIANA

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 2. Lógica Inteligente: ¿Estoy en Producción (AWS)?
if not DEBUG:  # <--- ESTA ES LA CLAVE
    # Si DEBUG es Falso (Servidor), usamos S3
    
    # Configuración AWS
    AWS_STORAGE_BUCKET_NAME = 'vadomdata' # O os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = 'us-east-1'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_DEFAULT_ACL = None
    
    # Sobrescribimos las URLs para apuntar a S3
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/geolab/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/geolab/media/'
    
    # Definimos los Storages de AWS
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "geolab/media",
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "geolab/static",
            },
        },
    }

else:
    # Si DEBUG es Verdadero (Tu PC), usamos almacenamiento local normal
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


AUTH_USER_MODEL = 'users.UsuarioBase'



# REDIRECCIONES DE LOGIN
# Al loguearse, ir al "router" que decide si es Staff o Cliente
LOGIN_REDIRECT_URL = 'home' 

# Al desloguearse, volver al login
LOGOUT_REDIRECT_URL = 'login' 

LOGIN_URL = 'login'

# Usar el modelo de usuario personalizado (Ya lo tenías, solo confirmo)
AUTH_USER_MODEL = 'users.UsuarioBase'


CSRF_TRUSTED_ORIGINS = [
    'https://portalgeolab.com',
    'https://www.portalgeolab.com',
]


# ============================================
# CONFIGURACIÓN DE EMAIL
# ============================================
# Para desarrollo: usa consola (muestra emails en terminal)
# Para producción: configura SMTP real

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = 'Geolab S.A.S <noreply@geolab.com>'


# ── Conversión de informes XLSX → PDF (LibreOffice headless) ──────────────────
# Ruta al ejecutable de LibreOffice (soffice). Si queda vacío, el sistema busca
# 'soffice'/'libreoffice' en el PATH; si no lo encuentra, genera solo el XLSX.
# Windows (instalación típica): C:\Program Files\LibreOffice\program\soffice.exe
LIBREOFFICE_PATH = config('LIBREOFFICE_PATH', default=None)


