# Generated by Django 6.0 on 2026-01-11 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0002_alter_muestra_options_alter_muestra_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_formato', models.CharField(default='F-GT-05', editable=False, max_length=20, verbose_name='Código de Formato')),
                ('version_formato', models.CharField(default='02', editable=False, max_length=10, verbose_name='Versión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de ensayos'), ('en_proceso', 'Ensayos en proceso'), ('completada', 'Ensayos completados'), ('informe_generado', 'Informe generado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero_informe', models.CharField(blank=True, max_length=50, verbose_name='Número de Informe')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_trabajo', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('remision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_trabajo', to='solicitudes.remisionmuestras', verbose_name='Remisión')),
            ],
            options={
                'verbose_name': 'Hoja de Trabajo',
                'verbose_name_plural': 'Hojas de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Muestra descartada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('diametro_d1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diámetro D1 (mm)')),
                ('diametro_d2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diámetro D2 (mm)')),
                ('diametro_d3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diámetro D3 (mm)')),
                ('longitud_l1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Longitud L1 (mm)')),
                ('longitud_l2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Longitud L2 (mm)')),
                ('longitud_l3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Longitud L3 (mm)')),
                ('peso_gramos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (g)')),
                ('carga_maxima_kn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Carga Máxima (KN)')),
                ('forma_falla', models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('tipo_1', 'Tipo 1 - Conos razonablemente bien formados en ambos extremos'), ('tipo_2', 'Tipo 2 - Cono bien formado en un extremo, fisuras verticales'), ('tipo_3', 'Tipo 3 - Fisuras verticales columnares en ambos extremos'), ('tipo_4', 'Tipo 4 - Fractura diagonal sin fisuras en los extremos'), ('tipo_5', 'Tipo 5 - Fracturas en los lados en las partes superior o inferior'), ('tipo_6', 'Tipo 6 - Similar al tipo 5 pero el extremo del cilindro es puntiagudo')], default='', max_length=20, verbose_name='Forma de Falla')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_ensayo', models.DateField(blank=True, null=True, verbose_name='Fecha de Ensayo')),
                ('hoja_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='ensayos.hojatrabajo', verbose_name='Hoja de Trabajo')),
                ('muestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_ensayo', to='solicitudes.muestra', verbose_name='Muestra')),
            ],
            options={
                'verbose_name': 'Resultado de Muestra',
                'verbose_name_plural': 'Resultados de Muestras',
                'ordering': ['muestra__numero_muestra', 'muestra__edad_ensayo_dias'],
            },
        ),
    ]
