# Generated by Django 6.0 on 2026-01-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomuestra',
            name='seleccionado',
            field=models.BooleanField(default=False, verbose_name='Seleccionado para informe'),
        ),
    ]
