# Generated by Django 6.0.2 on 2026-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_add_seleccionado_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomuestra',
            name='distancia_falla_apoyo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia de la línea de falla al apoyo más próximo en mm', max_digits=7, null=True, verbose_name='Distancia falla-apoyo a (mm)'),
        ),
        migrations.AddField(
            model_name='resultadomuestra',
            name='formula_flexion',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('A', 'A - Falla en tercio medio'), ('B', 'B - Falla fuera del tercio medio')], default='', help_text='A: falla en tercio medio, B: falla fuera del tercio medio', max_length=1, verbose_name='Fórmula usada'),
        ),
        migrations.AddField(
            model_name='resultadomuestra',
            name='luz_entre_apoyos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia entre apoyos inferiores en mm', max_digits=7, null=True, verbose_name='Luz entre apoyos L (mm)'),
        ),
        migrations.AddField(
            model_name='resultadomuestra',
            name='tipo_especimen_viga',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('F', 'Fundido'), ('C', 'Cortado')], default='', help_text='F: Fundido, C: Cortado', max_length=1, verbose_name='Tipo espécimen'),
        ),
    ]
