# Generated by Django 6.0 on 2026-05-28 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ensayos', '0003_add_viga_fields_to_resultadomuestra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('ultimo', models.PositiveIntegerField(default=0, verbose_name='Último consecutivo')),
            ],
            options={
                'verbose_name': 'Consecutivo de Informe',
                'verbose_name_plural': 'Consecutivos de Informe',
            },
        ),
        migrations.CreateModel(
            name='InformeEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compresion_cilindros', 'Compresión de cilindros de concreto')], default='compresion_cilindros', max_length=30)),
                ('numero_informe', models.CharField(max_length=50, unique=True)),
                ('fecha_falla', models.DateField(verbose_name='Fecha de falla')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('archivo_xlsx', models.FileField(blank=True, null=True, upload_to='informes_ensayo/%Y/%m/')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes_ensayo/%Y/%m/')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_ensayo_generados', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_ensayo', to='core.obra')),
            ],
            options={
                'verbose_name': 'Informe de Ensayo',
                'verbose_name_plural': 'Informes de Ensayo',
                'ordering': ['-fecha_emision', '-id'],
                'unique_together': {('obra', 'tipo', 'fecha_falla')},
            },
        ),
        migrations.AddField(
            model_name='resultadomuestra',
            name='informe_ensayo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='ensayos.informeensayo', verbose_name='Informe de ensayo'),
        ),
    ]
