# Generated by Django 6.0 on 2026-01-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemisionMuestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_formato', models.CharField(default='F-GC-05', editable=False, max_length=20)),
                ('version_formato', models.CharField(default='01', editable=False, max_length=10)),
                ('orden_trabajo', models.CharField(max_length=50, verbose_name='Orden de Trabajo No.')),
                ('token_acceso', models.CharField(editable=False, max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada - Pendiente de respuesta'), ('completada', 'Completada'), ('vencida', 'Vencida')], default='borrador', max_length=20)),
                ('cc', models.CharField(blank=True, max_length=100, verbose_name='C.C.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('email_destinatario', models.EmailField(blank=True, max_length=254, verbose_name='Email del destinatario')),
                ('cliente_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha (Cliente)')),
                ('cliente_cantidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('cliente_estado', models.CharField(blank=True, max_length=100, verbose_name='Estado de muestras')),
                ('cliente_firma_nombre', models.CharField(blank=True, max_length=200, verbose_name='Firma (Nombre)')),
                ('cliente_observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('lab_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha recepción Lab')),
                ('lab_cantidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad recibida')),
                ('lab_estado', models.CharField(blank=True, max_length=100, verbose_name='Estado recibido')),
                ('lab_firma_nombre', models.CharField(blank=True, max_length=200, verbose_name='Recibido por')),
                ('lab_observaciones', models.TextField(blank=True, verbose_name='Observaciones Lab')),
                ('revisado_por', models.CharField(blank=True, max_length=200)),
                ('programado', models.BooleanField(default=False)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('firma_revision', models.CharField(blank=True, max_length=200)),
                ('firmante_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre completo del firmante')),
                ('firmante_cedula', models.CharField(blank=True, max_length=20, verbose_name='Cédula')),
                ('firmante_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('firmante_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del firmante')),
                ('firmante_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('firma_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firma_user_agent', models.TextField(blank=True)),
                ('firma_fecha', models.DateTimeField(blank=True, null=True)),
                ('acepta_veracidad', models.BooleanField(default=False, verbose_name='Acepta declaración de veracidad')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='core.obra')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remisión de Muestras',
                'verbose_name_plural': 'Remisiones de Muestras',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_muestra', models.PositiveIntegerField(verbose_name='Muestra No.')),
                ('tipo_muestra', models.CharField(choices=[('concreto', 'Concreto'), ('grouting', 'Grouting'), ('mortero', 'Mortero'), ('muretes', 'Muretes'), ('bloques', 'Bloques'), ('vigas', 'Vigas'), ('varilla', 'Varilla'), ('malla_elec', 'Malla Eléctrica')], max_length=20, verbose_name='Tipo de Muestra')),
                ('diametro_longitud', models.CharField(blank=True, max_length=50, verbose_name='Diámetro o Longitud (cm)')),
                ('ensayo_flexion', models.BooleanField(default=False, verbose_name='Flexión')),
                ('ensayo_compresion', models.BooleanField(default=False, verbose_name='Compresión')),
                ('ensayo_absorcion', models.BooleanField(default=False, verbose_name='Absorción')),
                ('ensayo_otros', models.CharField(blank=True, max_length=100, verbose_name='Otros ensayos')),
                ('localizacion', models.TextField(verbose_name='Localización de Muestra')),
                ('fecha_toma', models.DateField(verbose_name='Fecha de Toma')),
                ('edad_ensayo_dias', models.PositiveIntegerField(help_text='Ej: 7, 14, 28 días', verbose_name='Edad Ensayo (días)')),
                ('fc_resistencia', models.CharField(blank=True, help_text='Resistencia esperada', max_length=50, verbose_name="F'c (MPa/Psi)")),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='solicitudes.remisionmuestras')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['numero_muestra'],
                'unique_together': {('remision', 'numero_muestra')},
            },
        ),
    ]
