# Generated by Django 6.0 on 2026-01-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muestra',
            options={'ordering': ['numero_muestra', 'edad_ensayo_dias'], 'verbose_name': 'Muestra', 'verbose_name_plural': 'Muestras'},
        ),
        migrations.AlterUniqueTogether(
            name='muestra',
            unique_together={('remision', 'numero_muestra', 'edad_ensayo_dias')},
        ),
        migrations.AddField(
            model_name='muestra',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de cilindros/especímenes a fallar en esta edad', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='remisionmuestras',
            name='orden_trabajo',
            field=models.PositiveIntegerField(editable=False, help_text='Consecutivo automático por obra', verbose_name='Remision No.'),
        ),
        migrations.AlterUniqueTogether(
            name='remisionmuestras',
            unique_together={('obra', 'orden_trabajo')},
        ),
    ]
