# Generated by Django 6.0 on 2026-01-23 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_muestra_options_alter_muestra_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisionmuestras',
            name='email_destinatario',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del destinatario'),
        ),
        migrations.AlterField(
            model_name='remisionmuestras',
            name='token_acceso',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nueva_remision', 'Nueva Remision Recibida'), ('sistema', 'Notificacion del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('solo_staff', models.BooleanField(default=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('remision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='solicitudes.remisionmuestras')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
