# Generated by Django 6.0 on 2026-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_remisionmuestras_email_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='unidad_diametro',
            field=models.CharField(choices=[('mm', 'mm'), ('cm', 'cm'), ('pulg', 'pulg')], default='cm', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='diametro_longitud',
            field=models.CharField(blank=True, max_length=50, verbose_name='Diámetro o Longitud'),
        ),
    ]
