# Generated by Django 6.0.2 on 2026-04-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_muestra_unidad_diametro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='geometria',
            field=models.CharField(choices=[('cilindro', 'Cilindro'), ('cubo', 'Cubo'), ('prisma', 'Prisma')], default='cilindro', editable=False, max_length=20, verbose_name='Geometría del espécimen'),
        ),
    ]
