# Generated by Django 6.0.2 on 2026-04-03 16:41

from django.db import migrations


def backfill_geometria(apps, schema_editor):
    """Clasifica la geometría de todas las muestras existentes."""
    from ensayos.geometry import clasificar_geometria

    Muestra = apps.get_model('solicitudes', 'Muestra')
    for muestra in Muestra.objects.all().iterator():
        nueva_geometria = clasificar_geometria(
            muestra.diametro_longitud, muestra.unidad_diametro
        )
        if muestra.geometria != nueva_geometria:
            muestra.geometria = nueva_geometria
            muestra.save(update_fields=['geometria'])


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_add_geometria_to_muestra'),
    ]

    operations = [
        migrations.RunPython(backfill_geometria, migrations.RunPython.noop),
    ]
