# Generated by Django 6.0.2 on 2026-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_backfill_geometria_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='dimension_especimen',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('3_pulg', '3" (Cilindro)'), ('4_pulg', '4" (Cilindro)'), ('6_pulg', '6" (Cilindro)'), ('50_mm', '50mm (Cubo)'), ('15x15_cm', '15x15cm (Viga)')], default='', help_text='Seleccione la dimensión estándar', max_length=20, verbose_name='Dimensión del espécimen'),
        ),
    ]
