# Generated by Django 6.0.2 on 2026-04-03 20:33

from django.db import migrations


def backfill_dimension(apps, schema_editor):
    """
    Convierte datos legacy (diametro_longitud + unidad_diametro) al nuevo
    campo dimension_especimen para muestras existentes.
    """
    Muestra = apps.get_model('solicitudes', 'Muestra')

    for muestra in Muestra.objects.filter(dimension_especimen='').iterator():
        valor = (muestra.diametro_longitud or '').strip().lower()
        unidad = (muestra.unidad_diametro or '').strip().lower()

        dimension = ''

        if unidad == 'pulg':
            # Mapear pulgadas conocidas
            if valor in ('3', '3.0'):
                dimension = '3_pulg'
            elif valor in ('4', '4.0'):
                dimension = '4_pulg'
            elif valor in ('6', '6.0'):
                dimension = '6_pulg'

        elif 'x' in valor:
            # Formato AxB
            try:
                partes = valor.split('x')
                a = float(partes[0].strip())
                b = float(partes[1].strip())
                if unidad == 'cm':
                    a_mm, b_mm = a * 10, b * 10
                else:
                    a_mm, b_mm = a, b

                if abs(a_mm - 50) < 5 and abs(b_mm - 50) < 5:
                    dimension = '50_mm'
                elif abs(a_mm - 150) < 10 and abs(b_mm - 150) < 10:
                    dimension = '15x15_cm'
            except (ValueError, IndexError):
                pass

        elif valor:
            try:
                num = float(valor)
                if unidad == 'cm':
                    num_mm = num * 10
                elif unidad == 'mm':
                    num_mm = num
                else:
                    num_mm = 0

                if abs(num_mm - 50) < 5:
                    dimension = '50_mm'
                elif abs(num_mm - 150) < 10:
                    dimension = '15x15_cm'
                elif unidad == 'pulg' or num in (3, 4, 6):
                    # Heurística para datos sin unidad clara
                    if num == 3:
                        dimension = '3_pulg'
                    elif num == 4:
                        dimension = '4_pulg'
                    elif num == 6:
                        dimension = '6_pulg'
            except ValueError:
                pass

        if dimension:
            muestra.dimension_especimen = dimension
            muestra.save(update_fields=['dimension_especimen'])


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_add_dimension_especimen_to_muestra'),
    ]

    operations = [
        migrations.RunPython(backfill_dimension, migrations.RunPython.noop),
    ]
