# Generated by Django 6.0.2 on 2026-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_backfill_dimension_especimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='dimension_especimen',
            field=models.CharField(blank=True, choices=[('', '-- Seleccionar --'), ('3_pulg', '3" (Cilindro)'), ('4_pulg', '4" (Cilindro)'), ('6_pulg', '6" (Cilindro)'), ('50_mm', '50mm (Cubo)'), ('15x15_cm', '15x15cm (Viga)'), ('1_4_pulg', '1/4"'), ('3_8_pulg', '3/8"'), ('1_2_pulg', '1/2"'), ('5_8_pulg', '5/8"'), ('3_4_pulg', '3/4"'), ('7_8_pulg', '7/8"'), ('1_pulg', '1"'), ('1_1_4_pulg', '1 1/4"')], default='', help_text='Seleccione la dimensión estándar', max_length=20, verbose_name='Dimensión del espécimen'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='geometria',
            field=models.CharField(choices=[('cilindro', 'Cilindro'), ('cubo', 'Cubo'), ('prisma', 'Prisma'), ('acero', 'Acero (varilla/malla)')], default='cilindro', editable=False, max_length=20, verbose_name='Geometría del espécimen'),
        ),
    ]
