"""
Catálogo de servicios de la sede Bucaramanga.

Generado desde la hoja "LISTA DE PRECIO" de BASE DATOS BUCARAMANGA.xlsm
(solo categorías y servicios; los precios NO se importan aquí).

Limpieza aplicada sobre el Excel:
- Separadores de código normalizados a guion ("2.11" -> "2-11", "11,1,1L" -> "11-1-1L").
- Códigos "13-8"/"13-9" dentro de CONCRETOS (error de digitación) -> "1-3-9"/"1-3-10".
- Filas con el mismo nombre dentro de una categoría se fusionan (normas unidas con " / ").
- Nombres repetidos entre categorías reciben sufijo: "(Laboratorista)", "(Auxiliar)", etc.
- Códigos repetidos con distinto nombre reciben sufijo "-2".
- Norma "N/A" o vacía se guarda como cadena vacía.

Se carga con: python manage.py cargar_catalogo_bucaramanga
"""

# (codigo_categoria, nombre_categoria)
CATEGORIAS = [
    ('1', 'CONCRETOS'),
    ('2', 'SUELOS'),
    ('3', 'ASFALTOS Y MEZCLAS ASFÁLTICAS'),
    ('4', 'AGREGADOS PÉTREOS'),
    ('5', 'MAMPOSTERÍA'),
    ('6', 'MORTERO'),
    ('7', 'TRANSPORTE'),
    ('8A', 'ALQUILER DE EQUIPOS'),
    ('8V', 'VENTA DE EQUIPOS'),
    ('9', 'SISTEMA DE ANCLAJES PARA CONCRETO Y MAMPOSTERIA'),
    ('10', 'PERFORACIONES (NÚCLEOS) EN CONCRETO Y MAMPOSTERÍA'),
    ('11L', 'ASESORÍA EN OBRA - LABORATORISTA'),
    ('11A', 'ASESORÍA EN OBRA - AUXILIAR'),
    ('11B', 'ASESORÍA EN OBRA - LABORATORISTA MES'),
    ('12', 'CEMENTO'),
    ('13', 'ACERO'),
    ('14', 'ENSAYOS NO DESTRUCTIVOS'),
]

# (codigo_categoria, codigo_servicio, nombre, norma)
SERVICIOS = [
    # ── 1 ─────
    ('1', '1-1', 'Resistencia a la compresión de cilindros de concreto', 'NTC 673 - 2010'),
    ('1', '1-1-1', 'Ensayo compresión de testigos de cilindros de concreto', 'NTC 673 - 2017'),
    ('1', '1-1-2', 'resistencia a la compresión de cilindros de concretos con capin', ''),
    ('1', '1-2', 'Diseño de mezclas para dos agregados', ''),
    ('1', '1-2-1', 'Diseño de mezclas sin caracterizacion de agregados', ''),
    ('1', '1-3', 'Extracción de núcleos de concreto de 4" Compresion', 'NTC 3658 - 1994'),
    ('1', '1-3-1', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 2 1/2 y 3" (incluye refrentado)', 'NTC 3658 - 1994'),
    ('1', '1-3-2', 'Extracción de núcleos de concreto de 2 a 3"', 'NTC 3658 - 1994'),
    ('1', '1-3-3', 'Extracción de núcleos de concreto de 2" mas Compresion', 'NTC 3658 - 1994'),
    ('1', '1-3-4', 'Extracción de núcleos de concreto de 2 1/2" Sin compresion', 'NTC 3658 - 1995'),
    ('1', '1-3-5', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 1 A 2" (incluye refrentado)', 'NTC 3658 - 1995'),
    ('1', '1-3-6', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 2 1/4" A 3 (incluye refrentado)', 'NTC 3658 - 1995'),
    ('1', '1-3-7', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 2 " A 3 (incluye refrentado)', 'NTC 3658 - 1995'),
    ('1', '1-3-8', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 5" (incluye refrentado)', 'NTC 3658 - 1995'),
    ('1', '1-3-8-1', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 4" (incluye refrentado)', 'NTC 3658 - 1995'),
    ('1', '1-4', 'Corte de núcleos', 'NTC 3658 - 1994'),
    ('1', '1-5', 'Resistencia a la compresión de núcleos (incluye refrentado)', 'NTC 3658 - 1994'),
    ('1', '1-6', 'Densidad, absorción y contenido de vacíos permeables', ''),
    ('1', '1-7', 'Contenido de cemento en concreto endurecido', ''),
    ('1', '1-8', 'Resistencia a la flexión de vigas de concreto', 'NTC 3546-2003'),
    ('1', '1-9', 'Resistencia a la flexión del concreto', 'NTC 2871 - 2004'),
    ('1', '1-10', 'Refrentado cilindros de concreto 6", 4"', ''),
    ('1', '1-11', 'Absorción de energía - Tenacidad', 'NTC 5721 - 2009'),
    ('1', '1-12', 'Reactividad ALCALI - Silice', 'INV-E 234-2013'),
    ('1', '1-13', 'Reactividad potencial Alcali - Carbonato', 'ASTM C586-11'),
    ('1', '1-13-1', 'Diseño de mezclas para dos agregados 2(UND)', ''),
    ('1', '1-3-5-2', 'Extracción, corte y resistencia a la compresión de núcleos de concreto de 2 1/4 y 3" (incluye refrentado)', 'NTC 3658-2018'),
    ('1', '1-3-6-2', 'Módulo de Elasticidad Estático del concreto en cilindros a compresión', 'NTC 4025'),
    ('1', '1-3-7-2', 'Extracción de núcleos de concreto de 2 1/2" mas compresion', 'NTC 3658 - 1995'),
    ('1', '1-3-9', 'Extracción, Corte y resistencia a la compresion de núcleos de concreto de 2 a 3" (no incluye reparacion ) (2UND)', 'NTC 3658-1994'),
    ('1', '1-3-10', 'Traccion indirecta de especimenes de concreto', 'NTC -122-2000'),
    # ── 2 ─────
    ('2', '2-1', 'Contenido de Humedad', 'INV-E 122-2013'),
    ('2', '2-2', 'Límite líquido, plástico e índice de plasticidad', 'INV-E 125-126-2013 / NTC 4630 - 1999'),
    ('2', '2-3', 'Determinacion de los Tamaños de las Particulas de los Suelos (Granulometria por Tamizado e Hidrometro)', 'INV-E 123-2013'),
    ('2', '2-4', 'Ensayo de Compactación Próctor (Incluye Gravedad Especifica y % de Fracciones Finas y Gruesas)', 'INV-E 142-2013'),
    ('2', '2-5', 'Densidad y peso unitario del suelo en el terreno por método del cono de arena', 'INV-E 161-2013'),
    ('2', '2-5-1', 'Densidad y peso unitario del suelo en el terreno por método del cono de arena (Más de 5 unidades)', 'INV-E 161-2013'),
    ('2', '2-6', 'Apique en Material Granular ml', 'INV-E 101-2007'),
    ('2', '2-6-1', 'Apique manual (incluye toma de muestra y perfil estratigrafico)(UND) 1,5m de profundidad max 3 materiales terreno natural', 'INV-E 101-2007'),
    ('2', '2-7', 'Analisis Granulometríco de los Agregados Gruesos y Finos', 'INV-E 213-2013 / NTC 77 - 2007'),
    ('2', '2-8', 'Diseño de Mezclas de Suelo - Cemento sin Prueba de Durabilidad', ''),
    ('2', '2-8-1', 'Diseño de Mezclas de Suelo - Cemento', 'INV-E-614-2013'),
    ('2', '2-9', 'Relación de soporte del suelo CBR (Método I) (Incluye Proctor Gravedad Especifica y % de Fracciones Finas y Gruesas)', 'INV-E 148-2013'),
    ('2', '2-9-1', 'Relación de soporte del suelo CBR (Método I)', 'INV-E 148-2013'),
    ('2', '2-9-1-1', 'Cbr muestra inalterada', 'INV-E 148-2013'),
    ('2', '2-10', 'Compresion Inconfinada', 'INV-E 152-2013'),
    ('2', '2-11', 'Expansión libre en probeta', ''),
    ('2', '2-12', 'Peso Unitario', ''),
    ('2', '2-13', 'Limite de Contraccion', 'INV-E 127-2013'),
    ('2', '2-14', 'Contenido Organico de un Suelo Mediante el Ensayo de Perdida por Ignición', 'INV-E 121-2013'),
    ('2', '2-15', 'Penetrometro Dinamico de Cono en Aplicaciones de Pavimento a Poca Profundidad', 'INV-E 172-2013'),
    ('2', '2-16', 'Proporcion de Particulas Planas, Alargadas o Planas y Alargadas en Agregados Gruesos', 'INV-E 240-2013'),
    ('2', '2-17', 'Lavado Sobre el Tamiz 75um (200) en Agregados Minerales', 'NTC 78 - 1995'),
    ('2', '2-18', 'Medida del potencial de colapso de un suelo parcial mente saturado (no incluye densidad seca maxima)', 'INV-E 157-2013'),
    ('2', '2-19', 'Evaluacion de la resistencia mecanica de los agregados gruesos por metodo 10% de finos', 'INV-E 224-2013'),
    ('2', '2-20', 'Determinacion del contenido de vacios en agregados finos no compactados Angularidad de la fraccion Fina', 'INV-E 239-2013'),
    ('2', '2-21', 'Cantidad de particulas livianas en un agregado petreo', 'INV-E 221-2013'),
    ('2', '2-22', 'Sondeos con barreno manual , metro lineal de exploración (ml)', 'INV-E 110-2013'),
    ('2', '2-23', 'Perforaciones por rotación con broca, metro lineal', 'INV-E 108-2013'),
    ('2', '2-24', 'Perforaciones por percusión y lavado en suelos, metro lineal', ''),
    ('2', '2-25', 'Corte Directo consolidado Drenado', 'INV-E 154-2013'),
    ('2', '2-25-1', 'Corte Directo consolidado no Drenado', 'INV-E 154-2013'),
    ('2', '2-26', 'Contenido de sales solubles', 'INV-E 158-2013'),
    ('2', '2-28', 'Contenido de sulfatos (Incluye preparación de muestra)', 'INV-E 233-2013'),
    ('2', '2-29', 'Metodo para la determinación del índice Desleimientodurabilidad, de lutitas y otras rocas débiles', 'INV-E 236-2013'),
    ('2', '2-30', 'Contenido de materia orgánica con permanganato de Potasio', 'NLT-118-1991'),
    ('2', '2-31', 'Ensayo de placa', 'INV-E 168-2013'),
    ('2', '2-32', 'Determinacion del coeficiente de pulimiento acelerado (CPA) de las particulas de agregado grueso', 'INV-E 232-20213'),
    ('2', '2-33', 'Determinacion de la limpieza superficial de las partiulas de agregado grueso', 'INV-E 237-20213'),
    ('2', '2-34', 'Peso unitario de suelos metodo A', 'ASTM D 7263-2009'),
    ('2', '2-35', 'Peso unitario de suelos metodo B', 'ASTM D 7263-2009'),
    ('2', '2-36', 'Determinacion del contenido de materia organica por el metodo perganganato potasico ( un)', 'UNE EN 103204-219'),
    ('2', '2-37', 'Determinacion del PH en los suelos', ''),
    # ── 3 ─────
    ('3', '3-1', 'Inmersión - Compresión Sobre Mezclas Asfalticas en Caliente (6 Briquetas)', 'INV E 738-2013'),
    ('3', '3-2', 'Compactación de briquetas tipo Marshall', 'INV E 748-2013'),
    ('3', '3-3', 'Estabilidad - Flujo', 'INV E 733-2013--748-2013'),
    ('3', '3-4', 'Contenido de asfalto (Extracción)', 'INV E 732-2013'),
    ('3', '3-5', 'Análisis granulométrico de muestra de extracción', 'INV E 782-2013'),
    ('3', '3-6', 'Extracción de panelas', ''),
    ('3', '3-7', 'Extracción de núcleos', 'INV E 758-2013'),
    ('3', '3-8', 'Adherencia en bandeja', ''),
    ('3', '3-9', 'Gravedad específica Bulk y densidad de mezclas asfálticas compactadas no absorbentes', 'INV E 734 - 2013'),
    ('3', '3-10', 'Diseño de Mezclas Asfalticas Metodo Marschall', ''),
    ('3', '3-11', 'Traccion Indirecta en Seco por Briqueta (no Incluye Elaboracion)', 'INV E 725 - 2013'),
    ('3', '3-12', 'Traccion Indirecta en Inmersion por Briqueta (no Incluye Elaboracion)', 'INV E 725 - 2013'),
    ('3', '3-13-1', 'Porcentaje de vacios con aire en mezclas asfalticas compactadas densas y abiertas (No incluye ensayos adicionales)', 'INV E 736 - 2013'),
    ('3', '3-13', 'Gravedad específica Maxima de mezclas asfalticas para pavimentos (METODO RICE) por punto', 'INV E 736 - 2013'),
    ('3', '3-14', 'Espesr o Altura de núcleos de asfalto', 'INV E 744 - 2013'),
    ('3', '3-15', 'Densidades con Densimetro (menos de 5 unidades)', 'INV E 164-2013--166-2013'),
    ('3', '3-15-1', 'Densidades con Densimetro (mas de 6 unidades)', 'INV E 164-2013--166-2013'),
    ('3', '3-17', 'Ensayo de Deformación Plástica', 'INV E 756 - 2013'),
    ('3', '3-18', 'Ensayo de Módulo Resiliente en muestras de mezcla asfáltica (3 Temperaturas y 3 Frecuencias)', 'INV E 749-2013 / EN -12697-26'),
    ('3', '3-19', 'Contenido de agua en una emulsión asfáltica', 'INV E 761 - 2013'),
    ('3', '3-20', 'Ensayo Leyes de Fatiga, empleando probetas cilíndricas', 'EN -12697-24'),
    ('3', '3-21', 'Ensayo de Riego de Liga', 'IDU SECCIÓN 502-11'),
    ('3', '3-22', 'Viscosidad Saybolt Furol a 25 ºc', 'INV E 763 - 2013'),
    ('3', '3-23', 'Viscosidad Saybolt Furol a 50 ºC', 'INV E 763 - 2013'),
    ('3', '3-24', 'Tamizado de las emulsiones asfálticas', 'INV E 765 - 2013'),
    ('3', '3-25', 'Dosificacion de riesgo', ''),
    ('3', '3-26', 'Medida de la irregularidad superficial de un pavimento mediante la regla de tres metros estatica o radante', 'INV E 793 - 2013'),
    ('3', '3-27', 'Medida de la temperatura del aire, de la superficie y de una mezcla asfaltica', 'INV E 788 - 2013'),
    ('3', '3-28', 'Efecto del agua sobre las mezclas asfalticas sueltas', 'INV E 757 - 2013'),
    ('3', '3-29', 'Viscosidad absoluta a 60 ºC', 'INV E 711 - 2013'),
    ('3', '3-30', 'Viscosidad Cinemática', 'INV E 715 - 2013'),
    ('3', '3-31', 'Punto de ablandamiento promedio ºCUtilizando agua destilada', 'INV E 712 - 2013'),
    ('3', '3-32', 'Penetracion', 'INV E 706 - 2013'),
    ('3', '3-33', 'Textura superficial de un pavimento mediante el metodo circulo de arena', 'INV E 791 - 2013'),
    ('3', '3-34', 'Indice de rugosidad internacional - IRI', 'REV 4 2015-04-2019'),
    ('3', '3-35', 'Medida del coeficiente de resistencia al deslizamiento usando pendulo britanico', 'INV E 792:2013'),
    ('3', '3-36', 'Viscosidad saybolt furol a 135ºC', 'INV E 719:2013'),
    ('3', '3-37', 'Solubilidad en tricloroetileno', 'INV E 713:2013'),
    ('3', '3-38', 'Perdida por calentamiento en pelicula delgada y rotatoria (163ºC 5 horas)', 'INV E 720:2013'),
    ('3', '3-39', 'Viscosidad rotacional 163ºC (Pa.s) 3 temperaturas', 'INV E 717:2013'),
    ('3', '3-40', 'Viscosidad a 60ºC - 100ºC', 'INV E 716:2013'),
    ('3', '3-41', 'Ductilidad', 'INV E-702:2013'),
    ('3', '3-42', 'Ensayo de inmersión-compresión sobre mezclas asfálticas en caliente (Incluye Elaboración, 6 briquetas)', 'INV E-738:2013'),
    ('3', '3-43', 'Contenido de Agua en cementos asfálticos.', 'INV E-704:2013'),
    ('3', '3-44', 'Punto de ignición y de combustión mediante la copa abierta Cleveland', 'INV E-709:2013'),
    ('3', '3-45', 'Adhesividad de los ligantes bituminosos a los agregados finos (Método Riedel:Weber)', 'INV E-774:2013'),
    ('3', '3-46', 'Resistencia a la Fatiga de mezclas asfálticas sometidas a Flexión Dinámica empleando probetas prismáticas', 'EN -12697-24INV E-784:2007'),
    ('3', '3-47', 'Recuperación elástica por torsión', 'INV E-727:2013'),
    ('3', '3-48', 'Residuo por Destilación de emulsiones asfálticas', 'INV E-762:2013'),
    ('3', '3-49', 'Concentración crítica de llenante mineral.', 'INV E-745:2013'),
    ('3', '3-50', 'Afinidad con agregados pétreos, Adherencia en frasco (Stripping)', 'INV E-737:2007'),
    ('3', '3-51', 'Sedimentación en las emulsiones asfálticas', 'INV E-764:2013'),
    ('3', '3-52', 'Demulsibilidad de las emulsiones asfálticas', 'INV E-766:2013'),
    ('3', '3-53', 'Carga de partículas', 'INV E-767:2013'),
    ('3', '3-54', 'Determinación del PH', 'INV E-768:2013'),
    ('3', '3-55', 'Deformacion plastica-pista de ensayo de laboratorio', 'INV E-756:2013'),
    ('3', '3-56', 'Modulo resiliente en muestras de mezcla asfaltoca (3 Temperauras y 3 Frecuencias)', 'EN - 12697-26:2012'),
    ('3', '3-57', 'Efecto del Calor y del Aire Sobre el Asfalto en Lamina Delgada', 'INV E-721:2013'),
    ('3', '3-58', 'Densidad de Materiales Bituminosos Solidos y Semisolidos (MÉTODO DEL PICNÓMETRO)', 'INV E-707:2013'),
    ('3', '3-59', 'Contenido de Parafinas', 'INV E-718:2013'),
    ('3', '3-60', 'Humedad o Destilados Volatiles en Mezcas Asfalticas para Pavimentos', 'INV E-755:2013'),
    ('3', '3-61', 'Ensayo deflectométrico empleando el Deflectómetro de impacto ligero LWD para para dos (2) Puntos (Incluye transporte y disponibilidad de equipo y personal, Horario Diurno- Perimetro Urbano de Lunes a Viernes de 8:00am a 4:30pm )', 'UNE 103807-2'),
    ('3', '3-63', 'Módulo Dinámico (3 Temperaturas y 3 Frecuencias)', 'INV E-754:2007'),
    ('3', '3-64', 'Recuperación de asfalto para caracterización por evaporador rotatorio', 'INV E-759:2013'),
    ('3', '3-65', 'Resane Nucleo Extraccion (un)', ''),
    # ── 4 ─────
    ('4', '4-1', 'Contenido de materia orgánica por colorimetría', 'NTC 127'),
    ('4', '4-2', 'Determinación de la masa unitaria y los vacíos entre partículas de agregados', 'NTC 92 - 1995'),
    ('4', '4-3', 'Gravedad específica y absorción de agregados gruesos', 'NTC 176-1995 / INV E 223 - 2013'),
    ('4', '4-4', 'Gravedad específica y absorción de agregados finos', 'NTC 237-1995 / INV E 222 - 2013'),
    ('4', '4-5', 'Determinación de terrones de arcilla y partículas deleznables', 'INV E 211 - 2013'),
    ('4', '4-7', 'Determinacion del Contenido en Agregados Finos no Compactados Angularidad', 'INV E 239 - 2013'),
    ('4', '4-8', 'Sanidad de los agregados frente a la acción de soluciones de sulfato de sodio o magnesio - Solidez (5 ciclos)', 'INV E 220 - 2013'),
    ('4', '4-9', 'Equivalente de arena', 'INV E 133 - 2013'),
    ('4', '4-10', 'Porcentaje de caras fracturadas', 'INV E 227 - 2013'),
    ('4', '4-11', 'Índice de aplanamiento y alargamiento', 'INV E 230 - 2013'),
    ('4', '4-12', 'Resistencia al desgaste de los agregados en la Máquina de los Ángeles (sin trituración)', 'INV E 218 - 2013'),
    ('4', '4-13', 'Resistencia al desgaste de los agregados en la Máquina de los Ángeles (con trituración)', 'INV E 219 - 2013'),
    ('4', '4-14', 'Resistencia del agregado grueso al desgaste por abrasión con aparato Microdeval', 'INV E 238 - 2013'),
    ('4', '4-15', 'Valoración de elementos arcillosos por medio del azul de metileno', 'INV E 235 - 2013'),
    ('4', '4-16', 'Determinacion del Valor 10% finos', 'INV E 224 - 2013'),
    ('4', '4-17', 'Ánalisis petrográfico tamiz x tamiz con 2 secciones delgadas ( Gravas y arenas', 'ASTM C295-18'),
    ('4', '4-18', 'Ánalisis petrográfico tamiz x tamiz con 3 secciones delgadas ( Gravas y arenas', 'ASTM C295-18'),
    ('4', '4-19', 'Lavado sobre tamiz 75 um (200) en agregados minerales ( un)', 'INV E- 214 - 2013'),
    # ── 5 ─────
    ('5', '5-1', 'Compresión de bloques, ladrillos y adoquines de cemento y arcilla', 'NTC 4017 - 2005'),
    ('5', '5-2', 'Compresión de muretes sencillos', 'NTC 3495 - 2003'),
    ('5', '5-3', 'Absorción de bloques, ladrillos y adoquines', 'NTC 4017 - 2005'),
    ('5', '5-4', 'Flexion de Ladrillos y Adoquines en concreto', 'NTC 2017 - 2005'),
    ('5', '5-5', 'resistencia a la Abracion en Adoquines', ''),
    ('5', '5-6', 'Compresión de bloques, ladrillos de cemento', 'NTC 4024-01'),
    ('5', '5-7', 'Absorción de bloques, ladrillos y adoquines de cemento', 'NTC 4024-01'),
    ('5', '5-8', 'Flexion de unidades prefabricadas (bordillo/sardinel)', 'NTC 4109-2008'),
    ('5', '5-9', 'Compresion unidad mampostería prefabricados de concreto ( Incluye refrentado)', 'NTC 4024-1997'),
    ('5', '5-10', 'Resistencia a la compresion murete doble', 'NTC 4017-2005'),
    ('5', '5-11', 'Resisencia a la flexotraccion de losetas de concreto para pavimento', 'NTC 4992-2004'),
    ('5', '5-12', 'Flexion de baldosas de concreto', 'NTC 5147-2002'),
    ('5', '5-13', 'absorcion de baldosas de concreto', 'NTC 4992-2004'),
    ('5', '5-14', 'Resistencia ala abrasion en unidades de baldosas', 'NTC 5147-2002'),
    ('5', '5-15', 'Absorcion en agua de losetas de concretos (no incluye densidad', 'NTC 4992-2004'),
    ('5', '5-16', 'Absorcion en agua de losetas de concretos (incluye densidad', 'NTC 4992-2004'),
    # ── 6 ─────
    ('6', '6-1', 'Diseño de mezcla de mortero', ''),
    ('6', '6-2', 'Resistencia a la compresión de cilindros de mortero de cemento hidráulico', 'NTC 673-2010'),
    ('6', '6-3', 'Resistencia a la compresión de cubos de mortero', 'NTC 220 - 2004'),
    # ── 7 ─────
    ('7', '7-1', 'Transporte por viaje - Bucaramanga', ''),
    ('7', '7-1-1', 'Transporte por viaje obra', ''),
    ('7', '7-2-1', 'Transporte por viaje - Floridablanca y Girón', ''),
    ('7', '7-3', 'Transporte por viaje - Piedecuesta', ''),
    ('7', '7-3-1', 'Cobro entrada camioneta obra recogida de muestras', ''),
    ('7', '7-4', 'Transporte por viaje - Mesa de los Santos', ''),
    ('7', '7-5', 'Transporte por viaje - Lebrija', ''),
    ('7', '7-5-1', 'Transporte por viaje - Ruta del Cacao. Frentes 8', ''),
    ('7', '7-5-2', 'Transporte por viaje - Ruta del Cacao. Frentes 3 a 7', ''),
    ('7', '7-5-3', 'Transporte por viaje - Ruta del Cacao. Frentes 1 y 2', ''),
    ('7', '7-6', 'Transporte por viaje - San Alberto', ''),
    ('7', '7-6-1', 'Envio de equipo Ocaña', ''),
    ('7', '7-6-2', 'Muestras laboratorio - Bucaramanga', ''),
    ('7', '7-6-3', 'visita proyecto - Loma Cesar', ''),
    ('7', '7-6-4', 'Transporte por viaje - colorados (via al mar)', ''),
    ('7', '7-7', 'Transporte por viaje - obra toma anclajes', ''),
    ('7', '7-8', 'Transporte por viaje - Fundacion Magdalela', ''),
    ('7', '7-9', 'Transporte por viaje- entre bucaramanga y barrancabermeja', ''),
    ('7', '7-10', 'Transporte por viaje a municipio de cucuta', ''),
    ('7', '7-11', 'Transporte por viaje a municipio de barbosa', ''),
    ('7', '7-12', 'Transporte por viaje a municipio de san gil', ''),
    ('7', '7-13', 'Transporte bucaramanga - bogota / bogota - bucaramanga', ''),
    ('7', '7-14', 'Transporte de equipo bucaramanga - bogota / bogota - bucaramanga', ''),
    ('7', '7-15', 'Transporte por viaje - Bucaramanga-Giron-Floridablanca', ''),
    ('7', '7-16', 'Transporte por viaje entre Bucaramanga y Barrancabermeja', ''),
    ('7', '7-17', 'Transporte por viaje entre Bucaramanga y Barbosa', ''),
    ('7', '7-18', 'Transporte por viaje entre Bucaramanga y San Gil', ''),
    ('7', '7-19', 'Transporte por viaje entre Bucaramanga y Cucuta-el Zulia', ''),
    ('7', '7-20', 'Transporte por viaje terminal bucaramanga', ''),
    # ── 8A ─────
    ('8A', '8-1A', 'Día molde cilíndrico para ensayo de resistencia a compresión de concreto Ø=4"-6"', ''),
    ('8A', '8-2A', 'Mes molde cilíndrico para ensayo de resistencia a compresión de concreto. Ø=4" - Ø=6" (un)', ''),
    ('8A', '8-3A', 'Día molde cilíndrico para ensayo de resistencia a compresión de mortero. Ø=3" -4"', ''),
    ('8A', '8-4A', 'Día molde de vigas para ensayo de resistencia a flexión de concreto', ''),
    ('8A', '8-5A', 'Día aerómetro de presión (olla contenido de aire)', ''),
    ('8A', '8-6A', 'Dia Alquiler Equipo Varios (Validacion diseños) ciudad de Bucaramanga y aledaños', ''),
    ('8A', '8-7A', 'Dia Alquiler Equipó Varios (Validacion diseños) ciudad de Cucuta y aledaños', ''),
    ('8A', '8-8A', 'Alquiler cono de Marsh', ''),
    ('8A', '8-9A', 'Día Alquiler juego de moldes de cubos de mortero', ''),
    ('8A', '8-10A', 'Dia alquiler artesas 45x45', ''),
    ('8A', '8-11C', 'Día molde cilíndrico para ensayo de resistencia a compresión de concreto Ø=4"-6" metalicos', ''),
    ('8A', '8-11-1C', 'Día molde cilíndrico para ensayo de resistencia a compresión de concreto 6" metalicos', ''),
    ('8A', '8-10B', 'Mes alquiler prensa Hidraulica', ''),
    ('8A', '8-10C', 'Alquiler equipo incluye: prensa hidráulica para fallo cilindros de concreto, Equipo para toma de densidades ( cono y arena)', ''),
    ('8A', '8-11A', 'Alquiler cono de abrahams y varilla', ''),
    ('8A', '8-11B', 'Mantenimiento moldes (unidad)', ''),
    ('8A', '8-12B', 'Cobro cono (devuelto DAÑADO)', ''),
    ('8A', '8-120-B', 'Mantenimiento y adeccuacion de moldes metalicos (un)', ''),
    ('8A', '8-13B', 'Alquiler equipo Mezcladora eléctrica de 20L para Concreto (trompo) (DIA)', ''),
    ('8A', '8-14B', 'Cobro molde cubo de mortero (devuelto DAÑADO)', ''),
    ('8A', '8-15B', 'mes Alquiler Equipo para toma de densidades ( cono y arena)', ''),
    ('8A', '8-16B', 'Verificacion balanza 30 kg', ''),
    ('8A', '8-17B', 'Dia Alquiler Equipo para toma de densidades ( cono y arena)', ''),
    ('8A', '8-18B', 'Dia Alquiler planta electrica', ''),
    ('8A', '8-19B', "Cobro molde 4''metalicos (devuelto dañado)", ''),
    ('8A', '8-20B', "Mantenimiento y adecuacion de moldes metalicos de 6''", ''),
    ('8A', '8-21B', 'Balanza de 30 kg 1 (dia)', ''),
    ('8A', '8-22B', 'Gramera de 500g 1(dia)', ''),
    ('8A', '8-23B', 'Estufa electrica para humedades 1 (dia)', ''),
    ('8A', '8-24B', 'Cono de Abrams y Varilla compactadora 578-3/8, martillo de goma- cuchara metalica 1 (dia)', ''),
    ('8A', '8-25B', 'Termometro dia', ''),
    ('8A', '8-26B', 'Carretilla( dia)', ''),
    ('8A', '8-27B', 'Equipo de acentamiento(varilla, cuchara)', ''),
    ('8A', '828-B', 'Olla para masa unitaria 5L, 10L', 'NTC 1926'),
    # ── 8V ─────
    ('8V', '8-1V', 'Molde cilíndrico para ensayo de resistencia a compresión de concreto. Ø=6" metalico', ''),
    ('8V', '8-2V', 'Molde cilíndrico para ensayo de resistencia a compresión de concreto. Ø=4" metalico', ''),
    ('8V', '8-3V', 'Molde cilíndrico para ensayo de resistencia a compresión de mortero. Ø=3"', ''),
    ('8V', '8-4V', 'Molde de vigas para ensayo de resistencia a flexión de concreto', ''),
    ('8V', '8-5V', 'Molde cilíndrico para ensayo de resistencia a compresión de concreto Ø=4"-6"', ''),
    ('8V', '8-10V', 'Cono de Abrams y Varilla compactadora', ''),
    ('8V', '8-11V', 'Venta Varilla compactadora', ''),
    ('8V', '8-12V', 'Cuchara Toma Muestra Concreto', ''),
    ('8V', '8-13V', 'Termometro digital marca open', ''),
    ('8V', '8-14V', 'Molde cilíndrico plástico para ensayo de resistencia a compresión de concreto. Ø=4"', ''),
    ('8V', '8-15V', 'Venta de espatula', ''),
    ('8V', '8-16V', 'Venta cono slump - venta de varilla compactadora 5/8', ''),
    ('8V', '8-17V', 'Venta martillo de goma', ''),
    ('8V', '8-18V', 'Venta juego de moldes de 3 cubos de mortero ( hierro)', ''),
    ('8V', '8-19V', 'Venta juego de moldes de 3 cubos de mortero ( bronce)', ''),
    ('8V', '8-20V', 'Venta Termometro bimetalico', ''),
    ('8V', '8-21C', 'Calibracion termomometro cantidad de puntos de calibracion 3 dentro del intervalo acreditado', ''),
    # ── 9 ─────
    ('9', '9-1', 'Anclaje con broca de 1/4"', ''),
    ('9', '9-2', 'Anclaje con broca de 3/8"', ''),
    ('9', '9-3', 'Anclaje con broca de 1/2"', ''),
    ('9', '9-4', 'Anclaje con broca de 5/8"', ''),
    ('9', '9-5', 'Anclaje con broca de 3/4"', ''),
    ('9', '9-6', 'Anclaje con broca de 7/8"', ''),
    ('9', '9-7', 'Anclaje con broca de 1"', ''),
    ('9', '9-8', 'Anclaje con broca de 1 1/4"', ''),
    # ── 10 ─────
    ('10', '10-1', 'Perforación con broca de 1 1/2’’', ''),
    ('10', '10-2', 'Perforación con broca de 2’’', ''),
    ('10', '10-3', 'Perforación con broca de 2 1/2’’', ''),
    ('10', '10-4', 'Perforación con broca de 3’’', ''),
    ('10', '10-5', 'Perforación con broca de 3 1/2’’', ''),
    ('10', '10-6', 'Perforación con broca de 4’’', ''),
    ('10', '10-7', 'Perforación con broca de 4 1/2’’', ''),
    ('10', '10-8', 'Perforación con broca de 5’’', ''),
    ('10', '10-9', 'Perforación con broca de 5 1/2’’', ''),
    ('10', '10-10', 'Perforación con broca de 6’’', ''),
    ('10', '10-11', 'Perforación con broca de 7’’', ''),
    ('10', '10-12', 'Perforación con broca de 8’’', ''),
    # ── 11L ─────
    ('11L', '11-1L', 'Día personal calificado en ciudad de Bucaramanga y aledaños', ''),
    ('11L', '11-2L', 'Día personal calificado en ciudad de Barrancabermeja y aledaños', ''),
    ('11L', '11-3L', 'Día personal calificado en ciudad de Bogotá y aledaños', ''),
    ('11L', '11-4L', 'Día personal calificado en ciudad de Cúcuta y aledaños', ''),
    ('11L', '11-5L', 'Día personal calificado en La Lizama y aledaños', ''),
    ('11L', '11-6L', 'Día personal calificado en ciudad de Málaga y aledaños', ''),
    ('11L', '11-7L', 'Día personal calificado en proyecto Embalse de Bucaramanga - Río Tona', ''),
    ('11L', '11-8L', 'Día personal calificado en municipio de San Gil y aledaños', ''),
    ('11L', '11-9L', 'Día personal calificado en municipio de Aguachica y aledaños', ''),
    ('11L', '11-10L', 'Día personal calificado en obra: Ruta del Cacao', ''),
    ('11L', '11-10LV', 'Día personal calificado en obra: Ruta del Cacao. Disponibilidad de vehículo.', ''),
    ('11L', '11-10RC', 'Transportepor viaje- Ruta de Cacao. Frentes 8 y 9 (recoleccion de muestras)', ''),
    ('11L', '11-1-1L', 'Hora extra diurna personal calificado en obra - Laboratorista', ''),
    ('11L', '11-1-2L', 'Hora extra nocturna personal calificado en obra - Laboratorista', ''),
    ('11L', '11-1-3L', 'Hora dominicales personal calificado en obra - Laboratorista', ''),
    ('11L', '11-1-4L', 'Hora ordinaria domingos/festivos', ''),
    ('11L', '11-1-5L', 'Hora extra diurna domingos/festivos', ''),
    ('11L', '11-1-6L', 'Hora nocturna domingo/festivos', ''),
    ('11L', '11-1-7L', 'Hora extra nocturna domingo/festivos', ''),
    ('11L', '11-11LV', 'Medio día personal calificado en obra: Ruta del Cacao. Disponibilidad de vehículo.', ''),
    ('11L', '11-12RC', 'Medio dia Transportepor viaje- Ruta de Cacao. Frentes 8 y 9 (recoleccion de muestras)', ''),
    ('11L', '11-13LV', 'Transporte viaje - Ruta del cacao', ''),
    ('11L', '11-14V', 'Medio dia personal calificado en obra:no aplica horario extra', ''),
    # ── 11A ─────
    ('11A', '11-1A', 'Día personal calificado en ciudad de Bucaramanga y aledaños (Auxiliar)', ''),
    ('11A', '11-2A', 'Día personal calificado en ciudad de Barrancabermeja y aledaños (Auxiliar)', ''),
    ('11A', '11-3A', 'Día personal calificado en ciudad de Bogotá y aledaños (Auxiliar)', ''),
    ('11A', '11-4A', 'Día personal calificado en ciudad de Cúcuta y aledaños (Auxiliar)', ''),
    ('11A', '11-5A', 'Día personal calificado en municipio de La Lizama', ''),
    ('11A', '11-6A', 'Día personal calificado en ciudad de Málaga y aledaños (Auxiliar)', ''),
    ('11A', '11-7A', 'Día personal calificado en proyecto Embalse de Bucaramanga - Río Tona (Auxiliar)', ''),
    ('11A', '11-8A', 'Dia servicio labroratorio en obra', ''),
    ('11A', '11-10A', 'Día personal calificado en obra: Ruta del Cacao (Auxiliar)', ''),
    ('11A', '11-11A', 'Día personal calificado, equipo para tomade densidades(cono y arena)', ''),
    ('11A', '11-12A', 'Día personal calificado en obra: (No incluye horas extras ni festivos)', ''),
    ('11A', '11-13A', 'Medio día personal calificado en obra: (No incluye horas extras ni festivos)', ''),
    ('11A', '11-14A', 'Personal calificado en el municipio de barrancabermeja (no incluye horas extras ni dominicales', ''),
    ('11A', '11-15A', 'Transporte por viaje entre bucaramanga y barrancabermeja (Auxiliar)', ''),
    ('11A', '11-16A', 'Personal calificado con vehiculo ruta del cacao (no incluye horas extras ni dominicales) dia', ''),
    ('11A', '11-17A', 'Personal calificado en ciudad de bucaramanga y municipios aledaños (no incluye horas extras ni dominicales)', ''),
    ('11A', '11-18A', 'Personal calificado en municipio de barrancabermeja (no incluye horas extras ni dominicales)', ''),
    ('11A', '11-19A', 'Personal calificado en municipio de cucuta (no incluye horas extras ni dominicales)', ''),
    ('11A', '11-20A', 'Personal calificado en municipio de San Gil (no incluye horas extras ni dominicales)', ''),
    ('11A', '11-21A', 'Personal calificado en municipio de Barbosa (no incluye horas extras ni dominicales)', ''),
    ('11A', '11-21A-2', 'Personal calificado en municipio de GIRON (no incluye horas extras ni dominicales)', ''),
    # ── 11B ─────
    ('11B', '11-1B', 'Mes personal calificado en ciudad de Bucaramanga y aledaños', ''),
    ('11B', '11-2B', 'Mes personal calificado en ciudad de Barrancabermeja y aledaños', ''),
    ('11B', '11-3B', 'Mes personal calificado en ciudad de Cúcuta y aledaños', ''),
    ('11B', '11-4B', 'Mes personal calificado en ciudad de Bogotá y aledaños', ''),
    ('11B', '11-5B', 'Mes personal calificado en el municipio de San Andrés', ''),
    ('11B', '11-6B', 'Mes personal calificado en el municipio de Málaga', ''),
    ('11B', '11-7B', 'Mes servicio labroratorio en ciudad de Bucaramanga', ''),
    ('11B', '11-8B', 'Mes personal calificado en obra ( no incluye horas extras ni festivos)', ''),
    # ── 12 ─────
    ('12', '12-1', 'Finura - Aparato de Blaine', 'NTC 33 - 1997'),
    ('12', '12-2', 'Peso específico del cemento', 'NTC 221 - 1999'),
    ('12', '12-3', 'Finura de adición sobre tamiz No. 325', 'NTC 294 - 2005'),
    ('12', '12-4', 'Tiempo de fraguado - Método de agujas de Vicat', 'NTC 118 - 2004'),
    ('12', '12-5', 'Ensayos químicos - Óxidos de Magnesio', ''),
    ('12', '12-6', 'Ensayos químicos - Aluminato Tricálcico', ''),
    ('12', '12-7', 'Ensayos químicos - Trióxido de Azufre', ''),
    ('12', '12-8', 'Finura de adición sobre tamiz No. 200', 'NTC 294 - 2005'),
    ('12', '12-9', 'Fraguado Rapido del Cemento Hidraulico', 'NTC 297 - 1997'),
    ('12', '12-10', 'Consistencia Normal del Cemento Hidraulico', 'NTC 110 - 2013'),
    ('12', '12-11', 'Retenido sobre tamiz No. 45', 'NTC 294 - 2005'),
    # ── 13 ─────
    ('13', '13-1', 'Tensión en varillas corrugadas (hasta 1/2")', 'NTC 2289 - 2015'),
    ('13', '13-2', 'Tensión en varillas corrugadas (desde 5/8" hasta 1")', 'NTC 2289 - 2015'),
    ('13', '13-3', 'Tensión en varillas corrugadas (mayor a 1")', 'NTC 2289 - 2015'),
    ('13', '13-4', 'Doblamiento de acero', 'NTC 2289 - 2015'),
    ('13', '13-5', 'Resistencia al esfuerzo cortante en la soldadura de mallas electrosoldadas (4 pruebas)', 'NTC 5806 - 2010'),
    ('13', '13-6', 'Tensión en mallas electrosoldadas', 'NTC 5806 - 2010'),
    ('13', '13-7', 'Características físicas en aceros', ''),
    ('13', '13-8', 'Dobamiento de acero menor o igual a 1/2"', 'NTC 2289-2007'),
    ('13', '13-9', 'Doblamienton en mallas', 'NTC 3353-1997'),
    ('13', '13-10', 'Doblamiento para grafiles y grafiles en mallas electrosoldadas', 'NTC5806-2019'),
    ('13', '13-11', 'Tracción de barras de acero con conectores', 'NTC 2289 - 2020'),
    ('13', '13-12', 'Tracción de barras unidas mediante empalme roscado (hasta N8)', 'NTC 2289 - 2015'),
    ('13', '13-13', 'Tracción de barras unidas mediante empalme roscado (hasta N10)', 'NTC 2289 - 2015'),
    ('13', '13-14', 'Tracción de barras unidas mediante empalme roscado (hasta 1")', 'NTC 2289 - 2015'),
    # ── 14 ─────
    ('14', '14-1', 'Esclerometría (1 punto: 20 lecturas)', 'NTC 3692 - 1995'),
    ('14', '14-2', 'Ferroscan / Geo - radar dia max 20 lecturas', ''),
    ('14', '14-3', 'Ultrasonido', 'NTC 4325 - 1997'),
    ('14', '14-4', 'Carbonatación', 'UNE - 011 - 1997'),
    ('14', '14-5', 'Regatas para Verificacion de Diametros y Recubrimiento de Aceros', ''),
    ('14', '14-6', 'Determinacion de Dureza con Durometro (Propiedades de Caucho)', 'NTC 467 - 2006'),
    ('14', '14-7', 'Extraccion de Anclajes - Prueba de Carga en Barras Hasta 3/4', ''),
    ('14', '14-8', 'Extraccion de Anclajes - Prueba de Carga en Barras desde 7/8 Hasta 1"', ''),
    ('14', '14-11', 'Prueba de carga sistema de pasamanos, barandas, antepechos', 'CAPITULO B.4.2.2 DE LA NSR-10'),
]
